### PR TITLE
Add and improve more documentation, add TODOs and FIXMEs

### PR DESCRIPTION
**Pull request by spbnick**

### CODE REVIEW

**Comment by spbnick** [comment]
Thank you, Veronika. Yeah, I agree better naming would be good and not having to explain what we're looping through would be nice. I'm not sure how to help us make sure we fix this, though. Do you think filing an issue for refactoring the functions in question would help?

**Comment by spbnick** [comment]
Also, we need one approving review before we can merge this :)

**Comment by veruu** [comment]
Sure, adding the issue and mention it in the commit would be great! I'd say to add FIXMEs to some parts too, but we already have one comment on for loops, we don't need another and the issue will track that anyways. Can you do that and rebase so I can merge it? :)

**Comment by spbnick** [comment]
Alright, submitted #34. Please comment or submit a new issue if I missed something. Rebased as well. Thanks!

**Comment by veruu** [comment]
I additionally opened #35 for patchwork.py. Otherwise merging!

**Pull request merged**
